name: Dart Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Dart
      uses: dartsdk/setup-dart@v1
      with:
        sdk: stable

    - name: Dart analyze
      run: dart analyze

    - name: Dart test
      run: dart test
